# Generated by Django 3.0.4 on 2020-05-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200525_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlcontent',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
