# Generated by Django 3.0.4 on 2020-05-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_dlcontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlcontent',
            name='dl_archive',
            field=models.FileField(blank=True, null=True, upload_to='dlc/'),
        ),
    ]
