# Generated by Django 3.0.4 on 2020-05-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200525_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlcontent',
            options={'ordering': ['title']},
        ),
    ]
