# Generated by Django 3.0.4 on 2020-05-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200525_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='dl_content',
        ),
        migrations.DeleteModel(
            name='DlContent',
        ),
    ]
