# Generated by Django 3.0.4 on 2020-05-28 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_dlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='dlc_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.DLC'),
        ),
    ]
