# Generated by Django 3.0.4 on 2020-05-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_dlc_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlc',
            name='slug',
        ),
    ]
