# Generated by Django 3.0.4 on 2020-05-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_dlc_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlc',
            name='position',
        ),
    ]
