# Generated by Django 3.0.4 on 2020-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_dlc_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
