# Generated by Django 3.0.4 on 2020-05-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_dlc_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DLC',
        ),
    ]
