# Generated by Django 3.0.4 on 2020-05-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_delete_dlc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_url',
            new_name='video_id',
        ),
    ]
